[book]
authors = ["Daniel Eades"]
language = "en"
multilingual = false
src = "src"
title = "example"

[output.html]

[output.pdf]
optional = true

[preprocessor.d2]
command = "cargo run --manifest-path ../Cargo.toml"
file-extension = "png"
