version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: dtolnay/rust-toolchain
