version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore"
    include: "scope"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: dtolnay/rust-toolchain
  commit-message:
    prefix: "ci"
    include: "scope"
